spring.application.name=mycoolapp
#custom port
server.port = 8080
server.servlet.context-path=/mycoolapp

#actuators
#management.endpoints.web.exposure.include = health,info
#using wildcard to expose all endpoints "*"
management.endpoints.web.exposure.include = *
management.info.env.enabled = true


#info edit
info.app.name = My Cool App
info.app.description = A Crazy Cool Fun App
info.app.version = 1.0.0

#define custom properties

coach.name = Micky Mouse
team.name = The Mouse Club

